/**
 * Record this plugin's slice in .agent-adoptions.json and scaffold owed docs.
 */
import { spawnSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  hasTestCommand,
  mergeAdopted,
  PLUGIN_ID,
  propose as proposeBare,
  readRecord,
} from "./install_propose.mjs";
import { writePluginSlice } from "./adoptions.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const ASSETS = resolve(here, "../skills/documentation-intent/assets");
const INDEX_PY = resolve(here, "../skills/documentation-intent/scripts/docs_index.py");

const SKIP_ALWAYS = new Set(["INDEX.md", "THREAT-MODEL.md", "DATA-MODEL.md", "RUNBOOKS.md", "TROUBLESHOOTING.md"]);

function today() {
  return new Date().toISOString().slice(0, 10);
}

function packageName(projectDir) {
  const pkg = join(projectDir, "package.json");
  if (existsSync(pkg)) {
    try {
      const data = JSON.parse(readFileSync(pkg, "utf8"));
      if (typeof data.name === "string" && data.name) {
        return data.name;
      }
    } catch {
      /* ignore */
    }
  }
  return projectDir.split("/").filter(Boolean).at(-1) ?? "project";
}

function fillPlaceholders(text, sets) {
  return text.replace(/<!-- PROJECT:\s*([^>]+?)\s*-->/g, (full, inner) => {
    const key = inner.split("—")[0].split(",")[0].trim();
    if (sets[key]) {
      return sets[key];
    }
    return full;
  });
}

function copyFileIfMissing(from, to, sets, write) {
  if (existsSync(to)) {
    return "skipped";
  }
  if (!write) {
    return "created";
  }
  mkdirSync(dirname(to), { recursive: true });
  const raw = readFileSync(from, "utf8");
  writeFileSync(to, fillPlaceholders(raw, sets));
  return "created";
}

function walkCopy(srcDir, destDir, sets, { allowTesting, write }) {
  const created = [];
  function walk(dir) {
    for (const name of readdirSync(dir)) {
      const from = join(dir, name);
      const st = statSync(from);
      const rel = relative(srcDir, from);
      if (st.isDirectory()) {
        walk(from);
        continue;
      }
      if (name === "INDEX.md") {
        continue;
      }
      if (SKIP_ALWAYS.has(name) && name !== "TESTING.md") {
        continue;
      }
      if (name === "TESTING.md" && !allowTesting) {
        continue;
      }
      if (name === "ADR-0001-example.md") {
        continue;
      }
      const to = join(destDir, rel);
      const action = copyFileIfMissing(from, to, sets, write);
      created.push({ path: join("docs", rel), action });
    }
  }
  walk(srcDir);
  return created;
}

/**
 * Owed docs for a shape. `write: false` only reports what apply would create
 * (the plan a client shows before the operator confirms).
 */
export function scaffoldDocs(projectDir, shape, { write = true } = {}) {
  const sets = { name: packageName(projectDir), today: today() };
  const allowTesting = hasTestCommand(projectDir);
  const files = [];
  const rootFiles = (assetsRoot) => {
    for (const name of ["README.md", "AGENTS.md", "CHANGELOG.md"]) {
      files.push({
        path: name,
        action: copyFileIfMissing(join(assetsRoot, name), join(projectDir, name), sets, write),
      });
    }
  };
  if (shape === "single-file") {
    files.push({
      path: "DOCUMENTATION.md",
      action: copyFileIfMissing(join(ASSETS, "DOCUMENTATION.md"), join(projectDir, "DOCUMENTATION.md"), sets, write),
    });
    rootFiles(ASSETS);
    return files;
  }
  const root = shape === "flat" ? join(ASSETS, "flat") : ASSETS;
  rootFiles(root);
  files.push(...walkCopy(join(root, "docs"), join(projectDir, "docs"), sets, { allowTesting, write }));
  return files;
}

const GENERATED_INDEX = "<!-- Generated by docs_index.py";

/**
 * docs/INDEX.md is generated, but only when it is ours: an index the project
 * wrote itself is kept (`kept-foreign`) and named in the plan.
 */
export function indexPlan(projectDir, shape) {
  if (!shape || shape === "single-file") {
    return { path: "docs/INDEX.md", action: "skipped" };
  }
  const index = join(projectDir, "docs", "INDEX.md");
  if (!existsSync(index)) {
    return { path: "docs/INDEX.md", action: "created" };
  }
  const ours = readFileSync(index, "utf8").trimStart().startsWith(GENERATED_INDEX);
  return { path: "docs/INDEX.md", action: ours ? "regenerated" : "kept-foreign" };
}

function writeIndex(projectDir, shape) {
  const plan = indexPlan(projectDir, shape);
  if (plan.action === "skipped" || plan.action === "kept-foreign") {
    return { named: plan.action, ok: true };
  }
  if (!existsSync(INDEX_PY)) {
    return { named: "index-script-missing", ok: false };
  }
  const result = spawnSync("python3", [INDEX_PY, "--project", projectDir, "--write"], { encoding: "utf8" });
  return {
    named: result.status === 0 ? "wrote" : "index-failed",
    ok: result.status === 0,
    stderr: (result.stderr || "").trim(),
  };
}

export function agentsPointerPlan(projectDir) {
  return existsSync(join(projectDir, "AGENTS.md")) ? "skipped" : "created";
}

function ensureAgentsPointer(projectDir) {
  const action = agentsPointerPlan(projectDir);
  if (action === "created") {
    writeFileSync(join(projectDir, "AGENTS.md"), "This repository records plugin adoptions in `.agent-adoptions.json`.\n");
  }
  return action;
}

export function planFiles(projectDir, shape) {
  const files = shape
    ? scaffoldDocs(projectDir, shape, { write: false })
    : [{ path: "AGENTS.md", action: agentsPointerPlan(projectDir) }];
  files.push(indexPlan(projectDir, shape));
  return files;
}

export function propose(projectDir) {
  return proposeBare(projectDir, { planFiles });
}

export function apply(projectDirArg, answers) {
  const projectDir = resolve(projectDirArg || ".");
  const proposal = propose(projectDir);
  if (proposal.named === "foreign") {
    return { ok: false, named: "foreign", message: proposal.message, plugin: proposal.plugin };
  }

  const existing = readRecord(projectDir);
  const needsPick = (proposal.due ?? []).length > 0;
  if (needsPick && !Object.hasOwn(answers, "adopted")) {
    return {
      ok: false,
      named: "missing-answers",
      message: "Pass adopted in --answers, or run with --yes / -i.",
      plugin: proposal.plugin,
    };
  }

  const record = needsPick ? mergeAdopted(existing, answers) : existing ?? { adopted: {} };
  writePluginSlice(projectDir, PLUGIN_ID, record);

  const shape = record.adopted?.documentation?.shape;
  const files = shape ? scaffoldDocs(projectDir, shape) : [];
  const agentsPointer = ensureAgentsPointer(projectDir);
  const index = shape ? writeIndex(projectDir, shape) : { named: "skipped", ok: true };

  return {
    ok: index.ok,
    named: index.ok ? "ready" : "index-failed",
    plugin: proposal.plugin,
    record,
    files,
    agentsPointer,
    index,
  };
}
